version: "3.8"

services:
  db:
    image: postgres:15
    container_name: reminder-db
    restart: always
    environment:
      POSTGRES_USER: reminder
      POSTGRES_PASSWORD: reminder
      POSTGRES_DB: reminder
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reminder -d reminder"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reminder-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reminder-backend
    restart: always
    environment:
      DATABASE_URL: postgres://reminder:reminder@db:5432/reminder
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - reminder-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reminder-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - reminder-network

networks:
  reminder-network:
    driver: bridge
